// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epamgstrvmevylbewrxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwYW1nc3Rydm1ldnlsYmV3cnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMjczOTcsImV4cCI6MjA4NjkwMzM5N30.wtXqelwbwLmhSrQBwshr0vETxWKhuIi1lFL2Gaz00zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});